### ISSUE TITLE
Convert into JS / PHP / Java

### ISSUE THREAD

**Issue by ArkeologeN** [chao1995/chaochao#1]
Greet, I really loved your Kattis solution (https://github.com/chao1995/chaochao/blob/master/kattis/trainsorting.cpp) but as I'm not familiar enough with C++, I actually couldn't understand why you had to keep 2 vectors.

Would it be possible for you to translate this solution in JS / PHP / Java / Python please?

**Comment by chao1995** [comment]
Hi! The C++ code uses a slightly more complicated O(NlogN) algorithm to compute LIS. But since the problem constraints N only up to 2000, an O(N^2) algorithm is sufficient to AC.

The java version is here: d54e074a4974a526b44c2e74c88f237e5ed1a1ce
